### ISSUE TITLE
[Chore] Implement unit test for the crawler service

### ISSUE THREAD

**Issue by olivierobert** [nghiavt2906/Web-Scraping-BE#10]
## Issue

While there are numerous integration tests in the codebase, a significant missing part is testing for the code feature: scraping. 

## Expected

Unit or integration tests are implemented to verify that the crawler service performs as expected.

**Comment by nghiavt2906** [comment]
I have done adding the unit testing for the crawler. Please have a look:
https://github.com/nghiavt2906/Web-Scraping-BE/blob/master/src/services/crawler.test.js

**Comment by olivierobert** [comment]
I have reviewed the update. The implementation (with proper dependency injection) was improved too due to the testing need 💪 I have added one suggestion for your review.
