### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [nghiavt2906/Web-Scraping-BE#6]
Hello Nghia 👋 , thank you for your effort on the code submission. I am Olivier at Nimble, and am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need additional time, please let us know as soon as possible so we can plan accordingly.

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have now completed the first round of reviews. Please review all open issues on this repository and https://github.com/nghiavt2906/Web-Scraping-FE and provide your feedback to all of them. 

I am looking forward to hearing from you soon!

**Comment by nghiavt2906** [comment]
I have answered some of your issues. Could you have a quick look for discussion?
https://github.com/nghiavt2906/Web-Scraping-BE/issues/7
https://github.com/nghiavt2906/Web-Scraping-BE/issues/8

**Comment by olivierobert** [comment]
I have now reviewed all the feedback you added to most issues (no feedback was added for #11, though). There is now sufficient information for us to finalize this technical assessment stage. So the code review is now completed 🎉 

We appreciate your efforts on this code challenge 🙏 Our team will reach out to you in the coming days by email.

**Comment by nghiavt2906** [comment]
Thank you for your reviews and feedbacks. I want you to know that I have just also add my feedback for https://github.com/nghiavt2906/Web-Scraping-BE/issues/11 not long ago. So If possible, please take a look at that also.

**Comment by olivierobert** [comment]
I noticed the last pull request you made :-) It has been taken into account in our assessment.

It would have helped if you provide an update at the beginning of the code review process so that we could better assess how long you will need and which issues you plan to address or not.
