### ISSUE TITLE
[Question] Why not using an ORM for database operations?

### ISSUE THREAD

**Issue by olivierobert** [nghiavt2906/Web-Scraping-BE#8]
Part of the assessment is reviewing which libraries and tools are used to build the application. Battle-tested solutions such as Express were used, but database operations are performed without any abstraction layer. 

https://github.com/nghiavt2906/Web-Scraping-BE/blob/57c918214c75686543944fa0368f7b94fed78368/src/services/searchResults.js#L5-L13

Usually, most applications use an ORM such as [Prisma](https://www.prisma.io/) (favorite at @nimblehq), [Sequelize](https://sequelize.org/), or [TypeORM](https://typeorm.io/) to make database migrations and queries easier and bullet-proof.

**Comment by nghiavt2906** [comment]
The reason I did not use an ORM is that generally the application does not have complex queries and database design and most of them are read queries. I know how to use Sequelize to implement the model layer so in an application with lots of features I will definitely use ORM. I can implement the abstraction layer if you expect me to do.

**Comment by nghiavt2906** [comment]
Actually I only wrote sql queries for testing the scraping bot at first and implemented the ORM on a different branch. I should have forgot to merge into the main branch somehow. Please have a look at my updated code. Sorry for the mistake.

**Comment by olivierobert** [comment]
The replacement with Prisma looks good 👍 Again nothing wrong using SQL queries per se, I wanted to understand better your reasons for doing so.
